Add architecture input parameter
ok-nick/setup-aftman pull request #18
Opened 2024-08-22 21:51 UTC by TreehouseFalcon

## Proposed changes

This pull adds an `architecture` input parameter to allow a different arch choice than x86. It also updates the README to describe how to set this parameter.

2024-08-25 20:32 UTC, ok-nick requested changes
Hey, thanks for the contribution, these changes look good. Would you be able to reset the README.md to the main branch before this is merged.

2024-08-27 17:04 UTC, ok-nick approved these changes

2024-08-27 17:06 UTC, ok-nick commented
Aftman doesn't currently release aarch64 Windows builds, but that's fine for now

2024-08-27 17:07 UTC, merged

2024-09-11 18:55 UTC, TreehouseFalcon commented
> Would you be able to reset the README.md to the main branch before this is merged.
Sorry just saw this.
I'm looking to get some self-hosted arm64-based runners working for our studio so I figured I'd push this publicly so when arm gains wider adoption it'll be ready!